
export const CARD_BG = [
  { id: 1, bgcolor: 'linear-gradient(135deg, #16202a 0%, #1f2235 100%)' }, // Subtle Dark Navy
  { id: 2, bgcolor: 'linear-gradient(135deg, #2a3b4c 0%, #3b4d61 100%)' }, // Dark Navy to Cool Gray
  { id: 3, bgcolor: 'linear-gradient(135deg, #2e3f57 0%, #4a4e75 100%)' }, // Cyan hint to Soft Purple
  { id: 4, bgcolor: 'linear-gradient(135deg, #1f1c33 0%, #372b52 100%)' }, // Dark Navy to Muted Magenta
  { id: 5, bgcolor: 'linear-gradient(135deg, #27384e 0%, #3a3f68 100%)' }, // Cyan Blue toned down
  { id: 6, bgcolor: 'linear-gradient(135deg, #2b2b3c 0%, #383850 100%)' }, // Neutral soft dark
  { id: 7, bgcolor: 'linear-gradient(135deg, #212336 0%, #3d3567 100%)' }, // Purple hint subtle
  { id: 8, bgcolor: 'linear-gradient(135deg, #1d2735 0%, #2f3b50 100%)' }, // Cool tinted dark
  { id: 9, bgcolor: 'linear-gradient(135deg, #2f2c4f 0%, #463c6a 100%)' }, // Deep muted purple
  { id: 10, bgcolor: 'linear-gradient(135deg, #1f1f2b 0%, #332a46 100%)' }, // Magenta hint soft
];


export const APP_FEATURES = [
    {
        id: "01",
        title: "Tailored Just for You",
        description:
        "Get interview questions and model answers based on your role, experience, and specific focus areas - no generic practice here."
    },

     {
        id: "02",
        title: "Learn at Your Own Pace",
        description:
        "Expand answers only when you're ready. Dive deeper into any concept instantly with AI-powered detailed explanations."
    },

     {
        id: "03",
        title: "Capture Your Insights",
        description:
        "Add personal notes to any question and pin important ones to the top - making your learning more organized and impactful."
    },

     {
        id: "04",
        title: 'Understand the "Why" Behind Answers',
        description:
        "Beyond just answers - unlock detailed concept explanations generated by AI, helping you truly master each topic."
    },

     {
        id: "05",
        title: "Save, Organize, and Revisit",
        description:
        "Easily save your interview sets, organize them neatly in your dashboard, and pick up your preparation right where you left off."
    },
]